package org.sonarsource.solidity;

public class SolidityKeywords {

  private SolidityKeywords() {
  }

  public static String[] get() {
    String[] solidityKeywords = {
      "abstract",
      "catch",
      "final",
      "in",
      "let",
      "inline",
      "match",
      "type",
      "of",
      "null",
      "static",
      "relocatable",
      "try",
      "typeof",
      "protected",
      "inheritable",
      "pragma",
      "as",
      "import",
      "from",
      "contract",
      "interface",
      "library",
      "is",
      "using",
      "for",
      "struct",
      "constructor",
      "modifier",
      "function",
      "returns",
      "event",
      "enum",
      "mapping",
      "memory",
      "storage",
      "if",
      "else",
      "while",
      "assembly",
      "do",
      "return",
      "throw",
      "emit",
      "var",
      "address",
      "bool",
      "string",
      "byte",
      "new",
      "after",
      "delete",
      "switch",
      "case",
      "default",
      "anonymous",
      "break",
      "constant",
      "continue",
      "external",
      "indexed",
      "internal",
      "payable",
      "private",
      "public",
      "pure",
      "view"
    };
    return solidityKeywords;
  }
}
